<%@ Page Language="C#" AutoEventWireup="true" CodeFile="feedbackadmin.aspx.cs" Inherits="feedbackadmin" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Movie Portal</title>
    <style type="text/css">
        body,html{
             background-image: url("Images/ji.jpg");

    /* Full height */
    height: 100%; 

    /* Center and scale the image nicely */
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
        }
        .auto-style1 {
            margin-left: 315px;
            margin-top: 0px;
            margin-right: 315px;
        }
        
        .auto-style2 {
            color: #FFFFFF;
            font-size: xx-large;
            height: 500px;
        }
        .auto-style3 {
            text-decoration: none;
        }
        .auto-style4 {
            color: #FFFFFF;
        }
        </style>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <span class="auto-style2"><a href="afterloginadmin.aspx" class="auto-style3"><span class="auto-style4">Home</span></a></span><asp:GridView ID="GridView1" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateEditButton="True" AutoGenerateDeleteButton="True"  BackColor="White" BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px"   CellPadding="4" DataSourceID="SqlDataSource1" EnableModelValidation="True" ForeColor="Black" GridLines="Horizontal" Height="613px" Width="689px" CssClass="auto-style1" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" DataKeyNames="id">
                <Columns>
                    <asp:BoundField DataField="id" HeaderText="ID" SortExpression="id" InsertVisible="False" ReadOnly="True" />
                    <asp:BoundField DataField="name" HeaderText="NAME" SortExpression="name" />
                    <asp:BoundField DataField="feedback" HeaderText="FEEDBACK" SortExpression="feedback" />
                </Columns>
                <FooterStyle BackColor="#CCCC99" ForeColor="Black" />
                <HeaderStyle BackColor="#333333" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="White" ForeColor="Black" HorizontalAlign="Right" />
                <SelectedRowStyle BackColor="#CC3333" Font-Bold="True" ForeColor="White" />
            </asp:GridView>
        </div>
         
               <dd>
                  </dd>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:RegistrationConnectionString %>" SelectCommand="SELECT * FROM [guestfeedback]" DeleteCommand="DELETE FROM [guestfeedback] WHERE [id] = @id" InsertCommand="INSERT INTO [guestfeedback] ([name], [feedback]) VALUES (@name, @feedback)" UpdateCommand="UPDATE [guestfeedback] SET [name] = @name, [feedback] = @feedback WHERE [id] = @id">
            <DeleteParameters>
                <asp:Parameter Name="id" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="name" Type="String" />
                <asp:Parameter Name="feedback" Type="String" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="name" Type="String" />
                <asp:Parameter Name="feedback" Type="String" />
                <asp:Parameter Name="id" Type="Int32" />
            </UpdateParameters>
                   </asp:SqlDataSource>
    
    
    
 
    
    
    </form>
</body>
</html>
